In [73]:
## Pytorch fundamentals

Why use Pytorch?  
PyTorch helps take care of many things such as GPU acceleration (making your code run faster) behind the scenes.

In [74]:
print("I am excited to learn pytorch")

I am excited to learn pytorch


In [75]:
import torch
torch.__version__

'2.5.1+cu121'

Tensors are the fundamental building block of machine learning.

In [76]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


In [77]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [78]:
## Introduction to tensors

## Creating tensors

In [79]:
# scalar tensor
scalar=torch.tensor(7)
scalar

tensor(7)

In [80]:
scalar.ndim

0

In [81]:
# get tensor back as python int
scalar.item()

7

In [82]:
# Vector: a vector is a single dimension tensor but can contain many numbers

vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [83]:
vector.ndim

1

In [84]:
vector.shape

torch.Size([2])

In [85]:
# Matrix
MATRIX=torch.tensor([[2,3],[5,6]])
MATRIX

tensor([[2, 3],
        [5, 6]])

In [86]:
MATRIX.shape

torch.Size([2, 2])

In [87]:
MATRIX.ndim

2

In [88]:
MATRIX[0]

tensor([2, 3])

In [89]:
MATRIX[1]

tensor([5, 6])

In [90]:
MATRIX[1][1]

tensor(6)

In [91]:
# tensor
TENSOR=torch.tensor([[[1,2,3],[5,6,7]],
                     [[3,4,5],[6,7,8]]])
TENSOR


tensor([[[1, 2, 3],
         [5, 6, 7]],

        [[3, 4, 5],
         [6, 7, 8]]])

In [92]:
TENSOR.shape

torch.Size([2, 2, 3])

In [93]:
TENSOR.ndim

3

In [94]:
TENSOR[0]

tensor([[1, 2, 3],
        [5, 6, 7]])

In [95]:
TENSOR[1]

tensor([[3, 4, 5],
        [6, 7, 8]])

In [96]:
TENSOR[0][1]

tensor([5, 6, 7])

# Random tensors


  why random tensors?

  Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

In [97]:
# Create a random tensors with pytorch
random_tensor=torch.rand(size=(3,4))
random_tensor,random_tensor.dtype,random_tensor.ndim,random_tensor.shape

(tensor([[0.5802, 0.6191, 0.2372, 0.6137],
         [0.1218, 0.0635, 0.6794, 0.2473],
         [0.1606, 0.0617, 0.1828, 0.6408]]),
 torch.float32,
 2,
 torch.Size([3, 4]))

In [98]:
random_tensor.ndim

2

In [99]:
random_tensor.shape

torch.Size([3, 4])

In [100]:
random_tensor[0]

tensor([0.5802, 0.6191, 0.2372, 0.6137])

In [101]:
random_tensor[1][2]

tensor(0.6794)

In [102]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(3,224,224))
random_image_size_tensor

tensor([[[0.2888, 0.6166, 0.1952,  ..., 0.5276, 0.1974, 0.6465],
         [0.9707, 0.2999, 0.6473,  ..., 0.4698, 0.1765, 0.5435],
         [0.8052, 0.3595, 0.8786,  ..., 0.9991, 0.8750, 0.9045],
         ...,
         [0.9727, 0.5915, 0.2175,  ..., 0.8877, 0.8375, 0.6910],
         [0.7746, 0.5512, 0.6642,  ..., 0.9169, 0.1943, 0.1147],
         [0.2125, 0.3716, 0.3365,  ..., 0.7666, 0.8202, 0.3008]],

        [[0.0594, 0.1603, 0.4893,  ..., 0.8441, 0.0695, 0.6478],
         [0.6829, 0.0494, 0.5858,  ..., 0.4195, 0.9216, 0.6398],
         [0.1068, 0.4154, 0.1886,  ..., 0.3571, 0.4250, 0.0066],
         ...,
         [0.9032, 0.2346, 0.3518,  ..., 0.4143, 0.6267, 0.7931],
         [0.6287, 0.1919, 0.2580,  ..., 0.4419, 0.3287, 0.5381],
         [0.7124, 0.8997, 0.9666,  ..., 0.4629, 0.0341, 0.0698]],

        [[0.5543, 0.2590, 0.6815,  ..., 0.8274, 0.8889, 0.6655],
         [0.4573, 0.2849, 0.5455,  ..., 0.5954, 0.0787, 0.8411],
         [0.0615, 0.2669, 0.9574,  ..., 0.7451, 0.4761, 0.

In [103]:
random_image_size_tensor.shape

torch.Size([3, 224, 224])

In [104]:
random_image_size_tensor.ndim

3

In [105]:
# Creating tensors with ones and zeros
zero=torch.zeros(size=(4,3))
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [106]:
ones=torch.ones(size=(5,6))
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [107]:
ones.dtype

torch.float32

In [108]:
ones.ndim

2

In [109]:
zero.ndim

2

Creating a range and tensors like

In [110]:
# use torch.arange(), torch.range() is deprecated

zero_to_ten=torch.arange(0,10,1)
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
ten_zeros=torch.zeros_like(zero_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatypes

In [112]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor, float_32_tensor.shape,float_32_tensor.ndim

(tensor([3., 6., 9.]), torch.Size([3]), 1)

In [113]:
float_32_tensor.dtype,float_32_tensor.device

(torch.float32, device(type='cpu'))

PyTorch likes calculations between tensors to be on the same device

In [114]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float16) # torch.half would also work
float_16_tensor.dtype

torch.float16

In [115]:
tensor=torch.randn(size=(3,4))

print(tensor)
print(f"Shape of tensor :{tensor.shape}")
print(f"Datatype of a tensor: {tensor.dtype}")
print(f"Device tensor is stored on : {tensor.device}")

tensor([[ 1.8189,  0.8429, -1.4400,  0.9549],
        [ 1.6657,  0.1269, -0.4896, -0.8711],
        [ 0.0946,  0.6275,  1.7424, -1.6162]])
Shape of tensor :torch.Size([3, 4])
Datatype of a tensor: torch.float32
Device tensor is stored on : cpu


Manipulating Tensor

In [116]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [117]:
tensor*10

tensor([10, 20, 30])

In [118]:
tensor

tensor([1, 2, 3])

In [119]:
tensor=tensor+1
tensor

tensor([2, 3, 4])

In [120]:
tensor-10

tensor([-8, -7, -6])

In [121]:
torch.multiply(tensor,10)

tensor([20, 30, 40])

In [122]:
tensor

tensor([2, 3, 4])

In [123]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([2, 3, 4]) * tensor([2, 3, 4])
Equals: tensor([ 4,  9, 16])


Matrix Multiplication

In [124]:
import torch
tensor=torch.tensor([1,2,3,4])
tensor.shape

torch.Size([4])

In [125]:
# elelment wise multiplication
tensor*tensor

tensor([ 1,  4,  9, 16])

In [126]:
# Matrix multilication
torch.matmul(tensor,tensor)

tensor(30)

In [127]:
# We can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(30)

time comparison of matrix multiplication

In [130]:
%%time

value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
value

CPU times: user 2.21 ms, sys: 9 µs, total: 2.22 ms
Wall time: 1.84 ms


tensor(30)

In [131]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 90 µs, sys: 6 µs, total: 96 µs
Wall time: 99.2 µs


tensor(30)

Matrix multplication most common error

In [133]:
tensor_A=torch.tensor([[1,2],
                       [3,4],
                       [5,6]],dtype=torch.float32)

tensor_B=torch.tensor([[1,2],
                       [3,4],
                       [5,6]],dtype=torch.float32)

torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [134]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])


In [136]:
# view tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[1., 3., 5.],
        [2., 4., 6.]])


In [137]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 5., 11., 17.],
        [11., 25., 39.],
        [17., 39., 61.]])

Output shape: torch.Size([3, 3])


In [138]:
# We can also use torch.mm() instead of torch.matmult()
torch.mm(tensor_A,tensor_B.T)

tensor([[ 5., 11., 17.],
        [11., 25., 39.],
        [17., 39., 61.]])

In [139]:
torch.manual_seed(42)

linear=torch.nn.Linear(in_features=2,out_features=6)

x=tensor_A
output=linear(x)
print(x.shape)
print(output)
print(output.shape)

torch.Size([3, 2])
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)
torch.Size([3, 6])


Finding the min,max,mean,sum

In [142]:
x=torch.arange(0,1000,100)
x

tensor([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [144]:
print(f"Minimum : {x.min()}")
print(f"Maximum : {x.max()}")
print(f"Sum : {x.sum()}")
print(f"Mean :{x.type(torch.float).mean()}")

Minimum : 0
Maximum : 900
Sum : 4500
Mean :450.0


In [145]:
torch.max(x),torch.min(x),torch.mean(x.type(torch.float32)),torch.sum(x)

(tensor(900), tensor(0), tensor(450.), tensor(4500))

Positional min/max

In [149]:
tensor=torch.arange(10,1000,10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where max value occurs: {tensor.argmin()}")

Tensor: tensor([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130, 140,
        150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280,
        290, 300, 310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420,
        430, 440, 450, 460, 470, 480, 490, 500, 510, 520, 530, 540, 550, 560,
        570, 580, 590, 600, 610, 620, 630, 640, 650, 660, 670, 680, 690, 700,
        710, 720, 730, 740, 750, 760, 770, 780, 790, 800, 810, 820, 830, 840,
        850, 860, 870, 880, 890, 900, 910, 920, 930, 940, 950, 960, 970, 980,
        990])
Index where max value occurs: 98
Index where max value occurs: 0


In [150]:
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [153]:
# Create a float16 tensor
tensor_float16=tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [154]:
# create an int8 tensor
tensor_int8=tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

Reshaping, stacking , squeezing and unsequeezing

In [161]:
import torch
x=torch.arange(1.,9.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8.]), torch.Size([8]))

In [163]:
# add an extra dimension
x_reshaped=x.reshape(1,8)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8.]]), torch.Size([1, 8]))

In [164]:
z=x.view(8,1) # we can also change the view by passing the dimesion in which we want to see

In [165]:
z

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]])

In [167]:
z=x.view(2,4)
z

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [168]:
z[0][0]=5.
z

tensor([[5., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [170]:
# stack
x_stacked=torch.stack([x,x,x,x,x,x],dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8.],
        [5., 2., 3., 4., 5., 6., 7., 8.],
        [5., 2., 3., 4., 5., 6., 7., 8.],
        [5., 2., 3., 4., 5., 6., 7., 8.],
        [5., 2., 3., 4., 5., 6., 7., 8.],
        [5., 2., 3., 4., 5., 6., 7., 8.]])

In [171]:
#stack
x_stacked=torch.stack([x,x,x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5., 5., 5.],
        [2., 2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4., 4.],
        [5., 5., 5., 5., 5., 5.],
        [6., 6., 6., 6., 6., 6.],
        [7., 7., 7., 7., 7., 7.],
        [8., 8., 8., 8., 8., 8.]])

In [172]:
x_stacked=torch.stack([x,x,x,x,x,x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8.],
        [5., 2., 3., 4., 5., 6., 7., 8.],
        [5., 2., 3., 4., 5., 6., 7., 8.],
        [5., 2., 3., 4., 5., 6., 7., 8.],
        [5., 2., 3., 4., 5., 6., 7., 8.],
        [5., 2., 3., 4., 5., 6., 7., 8.]])

In [174]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape : {x_reshaped.shape}")

# Remove extra dimension form x_reshaped
x_squeezed=x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8.]])
Previous shape : torch.Size([1, 8])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8.])
New shape: torch.Size([8])


In [177]:
# unsqueeze

print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8.])
Previous shape: torch.Size([8])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8.]])
New shape: torch.Size([1, 8])


In [178]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=1)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8.])
Previous shape: torch.Size([8])

New tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.]])
New shape: torch.Size([8, 1])


In [179]:
# Permute
x=torch.rand(size=(224,224,3))
x_permuted=x.permute(2,0,1)
print(f"Previous shaope: {x.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shaope: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


Indexing(select data from tensors)

In [1]:
import torch
x=torch.arange(1,10)
x=x.reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [2]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}")
print(f"Second square bracket: {x[0][0]}")
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1


In [3]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

tensor([[1, 2, 3]])

In [4]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [5]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [6]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])

Pytorch tensors and NumPy

In [9]:
import torch
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array) # numpy to tensor
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Note: By default, NumPy arrays are created with the datatype float64 and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).

However, many PyTorch calculations default to using float32.

So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use tensor = torch.from_numpy(array).type(torch.float32).

In [12]:
tensor=torch.from_numpy(array).type(torch.float32)
tensor,tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.float32)

In [13]:
# tensor to numpy
tensor=torch.ones(10)
numpy_array=tensor.numpy()
tensor,numpy_array

(tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Reproducibility

In [14]:
import torch

A=torch.rand(3,4)
B=torch.rand(3,4)

print(f"DOes Tensor A equals to B? ")
A==B

DOes Tensor A equals to B? 


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [17]:
import torch
import random

# Set the random seed
RANDOM_SEED=420 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8054, 0.1990, 0.9759, 0.1028],
        [0.3475, 0.1554, 0.8856, 0.6876],
        [0.2506, 0.1133, 0.2105, 0.4035]])

Tensor D:
tensor([[0.8054, 0.1990, 0.9759, 0.1028],
        [0.3475, 0.1554, 0.8856, 0.6876],
        [0.2506, 0.1133, 0.2105, 0.4035]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [1]:
!nvidia-smi

'nvidia-smi' is not recognized as an internal or external command,
operable program or batch file.


In [2]:
# check for GPU
import torch
torch.cuda.is_available()

True

In [3]:
#set the device type
device="cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# count the number of devices
torch.cuda.device_count()

1